// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUyPS7zmpO-LK88RY88Wpm1y2yw7hVpQ',
    appId: '1:946930548836:web:642962e934962f65b91f71',
    messagingSenderId: '946930548836',
    projectId: 'tutorconnectapp-ceca4',
    authDomain: 'tutorconnectapp-ceca4.firebaseapp.com',
    storageBucket: 'tutorconnectapp-ceca4.firebasestorage.app',
    measurementId: 'G-D09S8GN25F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfFFmqABHV02ylxt7Jx6EyPp8X_2XFc8E',
    appId: '1:946930548836:android:0f26c3a6de95ed91b91f71',
    messagingSenderId: '946930548836',
    projectId: 'tutorconnectapp-ceca4',
    storageBucket: 'tutorconnectapp-ceca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-M8bgQVDT7kX6HdI4WatpDxT6-hwcdww',
    appId: '1:946930548836:ios:37d5e614438a0241b91f71',
    messagingSenderId: '946930548836',
    projectId: 'tutorconnectapp-ceca4',
    storageBucket: 'tutorconnectapp-ceca4.firebasestorage.app',
    iosBundleId: 'com.example.tutorconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-M8bgQVDT7kX6HdI4WatpDxT6-hwcdww',
    appId: '1:946930548836:ios:37d5e614438a0241b91f71',
    messagingSenderId: '946930548836',
    projectId: 'tutorconnectapp-ceca4',
    storageBucket: 'tutorconnectapp-ceca4.firebasestorage.app',
    iosBundleId: 'com.example.tutorconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiUyPS7zmpO-LK88RY88Wpm1y2yw7hVpQ',
    appId: '1:946930548836:web:0ef7cd7c2d6c45f9b91f71',
    messagingSenderId: '946930548836',
    projectId: 'tutorconnectapp-ceca4',
    authDomain: 'tutorconnectapp-ceca4.firebaseapp.com',
    storageBucket: 'tutorconnectapp-ceca4.firebasestorage.app',
    measurementId: 'G-39W14GPWXE',
  );

}